trigger:
  - main

pool:
  vmImage: ubuntu-latest

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '16.x'
    displayName: 'Install Node.js'

  - task: SonarCloudPrepare@3
    inputs:
      SonarCloud: 'SonarQube Cloud service'
      organization: 'mohamedkhemaissia'
      scannerMode: 'CLI'
      configMode: 'manual'
      cliProjectKey: 'mohamedkhemaissia_DevopsJava'
      cliProjectName: 'DevopsJava Angular'
      cliSources: '.'
    displayName: 'Préparer SonarCloud'

  - script: |
      curl -sL https://sonarcloud.io/static/cpp/sonar-scanner-5.0.1.3006-linux.zip -o sonar-scanner.zip
      unzip sonar-scanner.zip
      export PATH=$PATH:$PWD/sonar-scanner-5.0.1.3006-linux/bin
    displayName: 'Installer sonar-scanner'

  - script: |
      cd angular-app-kubernetes
      sonar-scanner
    displayName: 'Lancer SonarCloud Scan'

  - task: SonarCloudAnalyze@3
    displayName: 'Analyser avec SonarCloud'

  - task: SonarCloudPublish@3
    inputs:
      pollingTimeoutSec: '300'
    displayName: 'Publier résultats SonarCloud'

  - script: |
      cd angular-app-kubernetes
      npm ci
      npm run build -- --configuration production
    displayName: 'Install dependencies and build Angular app'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: 'angular-app-kubernetes/dist/angular-app'
      ArtifactName: 'angular-build-dist'
      publishLocation: 'Container'
    displayName: 'Publier le build Angular comme artefact'